/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n\tquery CurrentUser {\n\t\tViewer {\n\t\t\tid\n\t\t\tname\n\t\t\tavatar {\n\t\t\t\tlarge\n\t\t\t\tmedium\n\t\t\t}\n\t\t\tbannerImage\n\t\t\toptions {\n\t\t\t\tdisplayAdultContent\n\t\t\t}\n\t\t\tsiteUrl\n\t\t}\n\t}\n": typeof types.CurrentUserDocument,
    "\n\tquery FeaturedAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(sort: FAVOURITES_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": typeof types.FeaturedAnimeDocument,
    "\n\tquery TrendingAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(sort: TRENDING_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": typeof types.TrendingAnimeDocument,
    "\n\tquery PopularAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(sort: POPULARITY_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": typeof types.PopularAnimeDocument,
    "\n\tquery UpcomingAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(\n\t\t\t\tstatus: NOT_YET_RELEASED\n\t\t\t\tsort: POPULARITY_DESC\n\t\t\t\ttype: ANIME\n\t\t\t) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": typeof types.UpcomingAnimeDocument,
    "\n\tquery ReleasingAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(status: RELEASING, sort: POPULARITY_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": typeof types.ReleasingAnimeDocument,
    "\n\tquery SearchAnime($anime: String, $page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(\n\t\t\t\tsearch: $anime\n\t\t\t\ttype: ANIME\n\t\t\t\tsort: SEARCH_MATCH\n\t\t\t\tisAdult: false\n\t\t\t) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": typeof types.SearchAnimeDocument,
    "\n\tquery SearchAnimeByGenre($genre: String, $page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(genre: $genre, sort: TRENDING_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": typeof types.SearchAnimeByGenreDocument,
    "\n\tquery SearchAnimeByID($id: Int) {\n\t\tMedia(id: $id, type: ANIME) {\n\t\t\tid\n\t\t\ttitle {\n\t\t\t\tromaji\n\t\t\t\tenglish\n\t\t\t\tnative\n\t\t\t\tuserPreferred\n\t\t\t}\n\t\t\tformat\n\t\t\tstatus\n\t\t\tdescription\n\t\t\tstartDate {\n\t\t\t\tyear\n\t\t\t\tmonth\n\t\t\t\tday\n\t\t\t}\n\t\t\tendDate {\n\t\t\t\tyear\n\t\t\t\tmonth\n\t\t\t\tday\n\t\t\t}\n\t\t\tseason\n\t\t\tseasonYear\n\t\t\tepisodes\n\t\t\tduration\n\t\t\tcoverImage {\n\t\t\t\tlarge\n\t\t\t\textraLarge\n\t\t\t\tcolor\n\t\t\t}\n\t\t\tbannerImage\n\t\t\tgenres\n\t\t\tsynonyms\n\t\t\taverageScore\n\t\t\tmeanScore\n\t\t\tpopularity\n\t\t\tfavourites\n\t\t\tisAdult\n\t\t\tnextAiringEpisode {\n\t\t\t\tid\n\t\t\t\ttimeUntilAiring\n\t\t\t\tepisode\n\t\t\t}\n\t\t\tmediaListEntry {\n\t\t\t\tid\n\t\t\t\tmediaId\n\t\t\t\tstatus\n\t\t\t\tscore(format: POINT_10)\n\t\t\t\tprogress\n\t\t\t}\n\t\t\tsiteUrl\n\t\t\ttrailer {\n\t\t\t\tid\n\t\t\t\tsite\n\t\t\t\tthumbnail\n\t\t\t}\n\t\t\tstreamingEpisodes {\n\t\t\t\ttitle\n\t\t\t\tthumbnail\n\t\t\t}\n\t\t}\n\t}\n": typeof types.SearchAnimeByIdDocument,
};
const documents: Documents = {
    "\n\tquery CurrentUser {\n\t\tViewer {\n\t\t\tid\n\t\t\tname\n\t\t\tavatar {\n\t\t\t\tlarge\n\t\t\t\tmedium\n\t\t\t}\n\t\t\tbannerImage\n\t\t\toptions {\n\t\t\t\tdisplayAdultContent\n\t\t\t}\n\t\t\tsiteUrl\n\t\t}\n\t}\n": types.CurrentUserDocument,
    "\n\tquery FeaturedAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(sort: FAVOURITES_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.FeaturedAnimeDocument,
    "\n\tquery TrendingAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(sort: TRENDING_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.TrendingAnimeDocument,
    "\n\tquery PopularAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(sort: POPULARITY_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.PopularAnimeDocument,
    "\n\tquery UpcomingAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(\n\t\t\t\tstatus: NOT_YET_RELEASED\n\t\t\t\tsort: POPULARITY_DESC\n\t\t\t\ttype: ANIME\n\t\t\t) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.UpcomingAnimeDocument,
    "\n\tquery ReleasingAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(status: RELEASING, sort: POPULARITY_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.ReleasingAnimeDocument,
    "\n\tquery SearchAnime($anime: String, $page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(\n\t\t\t\tsearch: $anime\n\t\t\t\ttype: ANIME\n\t\t\t\tsort: SEARCH_MATCH\n\t\t\t\tisAdult: false\n\t\t\t) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.SearchAnimeDocument,
    "\n\tquery SearchAnimeByGenre($genre: String, $page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(genre: $genre, sort: TRENDING_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.SearchAnimeByGenreDocument,
    "\n\tquery SearchAnimeByID($id: Int) {\n\t\tMedia(id: $id, type: ANIME) {\n\t\t\tid\n\t\t\ttitle {\n\t\t\t\tromaji\n\t\t\t\tenglish\n\t\t\t\tnative\n\t\t\t\tuserPreferred\n\t\t\t}\n\t\t\tformat\n\t\t\tstatus\n\t\t\tdescription\n\t\t\tstartDate {\n\t\t\t\tyear\n\t\t\t\tmonth\n\t\t\t\tday\n\t\t\t}\n\t\t\tendDate {\n\t\t\t\tyear\n\t\t\t\tmonth\n\t\t\t\tday\n\t\t\t}\n\t\t\tseason\n\t\t\tseasonYear\n\t\t\tepisodes\n\t\t\tduration\n\t\t\tcoverImage {\n\t\t\t\tlarge\n\t\t\t\textraLarge\n\t\t\t\tcolor\n\t\t\t}\n\t\t\tbannerImage\n\t\t\tgenres\n\t\t\tsynonyms\n\t\t\taverageScore\n\t\t\tmeanScore\n\t\t\tpopularity\n\t\t\tfavourites\n\t\t\tisAdult\n\t\t\tnextAiringEpisode {\n\t\t\t\tid\n\t\t\t\ttimeUntilAiring\n\t\t\t\tepisode\n\t\t\t}\n\t\t\tmediaListEntry {\n\t\t\t\tid\n\t\t\t\tmediaId\n\t\t\t\tstatus\n\t\t\t\tscore(format: POINT_10)\n\t\t\t\tprogress\n\t\t\t}\n\t\t\tsiteUrl\n\t\t\ttrailer {\n\t\t\t\tid\n\t\t\t\tsite\n\t\t\t\tthumbnail\n\t\t\t}\n\t\t\tstreamingEpisodes {\n\t\t\t\ttitle\n\t\t\t\tthumbnail\n\t\t\t}\n\t\t}\n\t}\n": types.SearchAnimeByIdDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery CurrentUser {\n\t\tViewer {\n\t\t\tid\n\t\t\tname\n\t\t\tavatar {\n\t\t\t\tlarge\n\t\t\t\tmedium\n\t\t\t}\n\t\t\tbannerImage\n\t\t\toptions {\n\t\t\t\tdisplayAdultContent\n\t\t\t}\n\t\t\tsiteUrl\n\t\t}\n\t}\n"): typeof import('./graphql').CurrentUserDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery FeaturedAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(sort: FAVOURITES_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): typeof import('./graphql').FeaturedAnimeDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery TrendingAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(sort: TRENDING_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): typeof import('./graphql').TrendingAnimeDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery PopularAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(sort: POPULARITY_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): typeof import('./graphql').PopularAnimeDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery UpcomingAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(\n\t\t\t\tstatus: NOT_YET_RELEASED\n\t\t\t\tsort: POPULARITY_DESC\n\t\t\t\ttype: ANIME\n\t\t\t) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): typeof import('./graphql').UpcomingAnimeDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery ReleasingAnime($page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(status: RELEASING, sort: POPULARITY_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): typeof import('./graphql').ReleasingAnimeDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery SearchAnime($anime: String, $page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(\n\t\t\t\tsearch: $anime\n\t\t\t\ttype: ANIME\n\t\t\t\tsort: SEARCH_MATCH\n\t\t\t\tisAdult: false\n\t\t\t) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): typeof import('./graphql').SearchAnimeDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery SearchAnimeByGenre($genre: String, $page: Int, $perPage: Int) {\n\t\tPage(page: $page, perPage: $perPage) {\n\t\t\tpageInfo {\n\t\t\t\ttotal\n\t\t\t\tcurrentPage\n\t\t\t\tlastPage\n\t\t\t\thasNextPage\n\t\t\t\tperPage\n\t\t\t}\n\t\t\tmedia(genre: $genre, sort: TRENDING_DESC, type: ANIME) {\n\t\t\t\tid\n\t\t\t\ttitle {\n\t\t\t\t\tromaji\n\t\t\t\t\tenglish\n\t\t\t\t\tnative\n\t\t\t\t\tuserPreferred\n\t\t\t\t}\n\t\t\t\tformat\n\t\t\t\tstatus\n\t\t\t\tdescription\n\t\t\t\tstartDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tendDate {\n\t\t\t\t\tyear\n\t\t\t\t\tmonth\n\t\t\t\t\tday\n\t\t\t\t}\n\t\t\t\tseason\n\t\t\t\tseasonYear\n\t\t\t\tepisodes\n\t\t\t\tduration\n\t\t\t\tcoverImage {\n\t\t\t\t\tlarge\n\t\t\t\t\textraLarge\n\t\t\t\t\tcolor\n\t\t\t\t}\n\t\t\t\tbannerImage\n\t\t\t\tgenres\n\t\t\t\tsynonyms\n\t\t\t\taverageScore\n\t\t\t\tmeanScore\n\t\t\t\tpopularity\n\t\t\t\tfavourites\n\t\t\t\tisAdult\n\t\t\t\tnextAiringEpisode {\n\t\t\t\t\tid\n\t\t\t\t\ttimeUntilAiring\n\t\t\t\t\tepisode\n\t\t\t\t}\n\t\t\t\tmediaListEntry {\n\t\t\t\t\tid\n\t\t\t\t\tmediaId\n\t\t\t\t\tstatus\n\t\t\t\t\tscore(format: POINT_10)\n\t\t\t\t\tprogress\n\t\t\t\t}\n\t\t\t\tsiteUrl\n\t\t\t\ttrailer {\n\t\t\t\t\tid\n\t\t\t\t\tsite\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t\tstreamingEpisodes {\n\t\t\t\t\ttitle\n\t\t\t\t\tthumbnail\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): typeof import('./graphql').SearchAnimeByGenreDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery SearchAnimeByID($id: Int) {\n\t\tMedia(id: $id, type: ANIME) {\n\t\t\tid\n\t\t\ttitle {\n\t\t\t\tromaji\n\t\t\t\tenglish\n\t\t\t\tnative\n\t\t\t\tuserPreferred\n\t\t\t}\n\t\t\tformat\n\t\t\tstatus\n\t\t\tdescription\n\t\t\tstartDate {\n\t\t\t\tyear\n\t\t\t\tmonth\n\t\t\t\tday\n\t\t\t}\n\t\t\tendDate {\n\t\t\t\tyear\n\t\t\t\tmonth\n\t\t\t\tday\n\t\t\t}\n\t\t\tseason\n\t\t\tseasonYear\n\t\t\tepisodes\n\t\t\tduration\n\t\t\tcoverImage {\n\t\t\t\tlarge\n\t\t\t\textraLarge\n\t\t\t\tcolor\n\t\t\t}\n\t\t\tbannerImage\n\t\t\tgenres\n\t\t\tsynonyms\n\t\t\taverageScore\n\t\t\tmeanScore\n\t\t\tpopularity\n\t\t\tfavourites\n\t\t\tisAdult\n\t\t\tnextAiringEpisode {\n\t\t\t\tid\n\t\t\t\ttimeUntilAiring\n\t\t\t\tepisode\n\t\t\t}\n\t\t\tmediaListEntry {\n\t\t\t\tid\n\t\t\t\tmediaId\n\t\t\t\tstatus\n\t\t\t\tscore(format: POINT_10)\n\t\t\t\tprogress\n\t\t\t}\n\t\t\tsiteUrl\n\t\t\ttrailer {\n\t\t\t\tid\n\t\t\t\tsite\n\t\t\t\tthumbnail\n\t\t\t}\n\t\t\tstreamingEpisodes {\n\t\t\t\ttitle\n\t\t\t\tthumbnail\n\t\t\t}\n\t\t}\n\t}\n"): typeof import('./graphql').SearchAnimeByIdDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
